### ISSUE TITLE
Collect Import: add collect-data to file types to be imported

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1077]
currently there are the following 2 data types to be imported: .collect, .collect-backup

We need to import also .collect-data
because it also contains the survey structure (+data)

**Comment by SteRiccio** [comment]
The .collect-data extension is used even when the data is exported by Collect Mobile; in that case the survey is not complete (the code list items are not exported for example).
Additionally, the .collect-data file can be generated from Collect by filtering the existing records.
If we want to be sure to import the complete survey structure and all the recorded data, only .collect and .collect-backup files import can be allowed.
