### ISSUE TITLE
Validation report: changed REQUIRED property still in report

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1096]
In imported survey there is a coordinate attribute "location" which is REQUIRED. Validation report complains about missing values. I removed REQUIRED tag, and run Validation Report. The same error msg remains there.
 
![err1](https://user-images.githubusercontent.com/45661798/91024125-29915400-e600-11ea-97f9-4a79f6b01e1a.JPG)
![err2](https://user-images.githubusercontent.com/45661798/91024142-2dbd7180-e600-11ea-913c-9042bb2b34a1.JPG)

**Comment by SteRiccio** [comment]
Hi Lauri, have you published the survey after you removed the "Required" flag?

**Comment by SteRiccio** [comment]
We cannot reproduce this issue anymore in the new version of Arena (0.3.4)
