### ISSUE TITLE
Designer with table: show true number of columns

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1102]
In Designer with table there is count of columns as for a form. This number does not show number of columns in the table

![image](https://user-images.githubusercontent.com/45661798/91042662-d082e980-e61a-11ea-8bac-530a627a31b4.png)

It would be better to show true number of columns in this table.

**Comment by ramirobg94** [comment]
The number shown is the number of columns of the form. what do you think that is the right place to put the number of columns on the table. I think that 1 or more tables can be contained in a form page.
