### ISSUE TITLE
Designer: change order of entities

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1103]
It should be possible to change the order of entities, at least at the same level of hierarchy. 
Please see how this is implemented in Collect Survey Designer. 
So steps are:
1) select entity name in the hierarchy
2) with UP and DOWN buttons we can move the entity

**Comment by minotogna** [comment]
UP and DOWN arrows it's a bit old fashion, at least we can implement this with Drag&Drop

however a few considerations:

1. Allowing reorder at different levels of the hierarchy won't be possible for published surveys.
2. There's need to have edit button to allow the start of the switching, and save button to persist the change of the hierarchy.
3. After save, involved entities, their ancestors and descendants must be revalidated (all nodeDefs then?). 

A canditate component is: https://github.com/frontend-collective/react-sortable-tree
