### ISSUE TITLE
Expression editor: DELETE buttons disappear after clicking GROUP() twice

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1118]
This what's happens:
https://unfao-my.sharepoint.com/:w:/g/personal/lauri_vesa_fao_org/EYvAp64xwaVDgvVLSizDAikBWeBT-lFDXxCKSJCIgYEAJA?e=L9BhRC

**Comment by ramirobg94** [comment]
@laurivesa This was solved, or at least tried in a previous PR. Now you can deal with this situation in two ways.

Using the button to expand the panel, top-right corner.
<img width="878" alt="Captura de pantalla 2020-11-12 a las 14 35 52" src="https://user-images.githubusercontent.com/11272068/98946596-5f095780-24f4-11eb-9e7c-15286d867efc.png">

Or, horizontal scroll, if you click on a blank space of the panel, you can use the keyboard
