### ISSUE TITLE
Expression editor: Using individual elements of attribute type taxon, coordinate, date, time

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1128]
Taxon attribute is actually an array and now it cannot perform correctly in expressions, as in this: 
![image](https://user-images.githubusercontent.com/45661798/91421027-154a9280-e85e-11ea-90ba-c8951760c42e.png)

So this attribute 'my_species' should refer to the correct column in taxon table, as follows:
my_species@code
my_species@scientific_name
my_species@family
my_species@genus
(my_species@vernacular_name ??)

So above Expression Editor should look as follows:
my_species@scientific_name == "Pinus sylvestris"

 Please see also this:
http://www.openforis.org/support/questions/633/selecting-individual-elements-of-attribute-type-taxon 

***************************************
Similarly, coordinate data requires similar methods for its elements:
@x
@y
@srs

For example: we can have a validation rule that 
plot_measured_location/@y<60

**Comment by minotogna** [comment]
individual fields should be accessible in basic and advanced mode.
For composite types, in basic mode only inner fields should be visible
