### ISSUE TITLE
ExpressionEditor: group attributes by parent entity

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1129]
in Editor attributes are seen as a long list. I would be easier to use them if they are grouped by parent entity, and they become to the list in the same order as they they are in the entry form or in table. Now items are in alphabetic order (by parent entities). 
This is a very good example what we need:
see "Grouping with Category" at https://www.syncfusion.com/javascript-ui-controls/js-dropdown-list

**Comment by laurivesa** [comment]
Please see "Grouping with Category" at [https://www.syncfusion.com/javascript-ui-controls/js-dropdown-list](url) 
(https://www.syncfusion.com/javascript-ui-controls/js-dropdown-list)

**Comment by minotogna** [comment]
Which Editor are you referring to?

**Comment by minotogna** [comment]
This is the ExpressionEditor. The issue was not clear: renaming it

**Comment by minotogna** [comment]
Introduce `Select` component that wraps https://react-select.com/home
