### ISSUE TITLE
Expressions: isEmpty function to attributes 

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1160]
In APPLY WHEN expressions we need to check often if another entity is blank or not blank. So we need an "isEmpty" function for this case, see following case as an example:
https://levelup.gitconnected.com/different-ways-to-check-if-an-object-is-empty-in-javascript-e1252d1c0b34

There might be already a method in JS for this?

**Comment by minotogna** [comment]
isEmpty applies only to attributes
