### ISSUE TITLE
Survey: Clone

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1166]
This issue is linke to #1305.
Survey can be a template, and to that needs to be cloned. Hence a CLONE button is needed.

If a survey is a schema in PostgreSQL, can we just copy template schema into a new name?

**Comment by minotogna** [comment]
- [ ] In survey dashboard, add button on the right side of export 'Clone'
- [ ] Start Job to clone survey 
- [ ] Add e2e Test to check the clone is successfully executed
