### ISSUE TITLE
Export schema summary

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1201]
Similarly as in Collect Survey editor, the user needs to get the summary of schema into a CSV file. That is needed for documenting the database structure.

**Comment by minotogna** [comment]
Example of collect schema export 

[collect_template_1_update_schema_summary_2021-03-17T09_22_21.xlsx](https://github.com/openforis/arena/files/6177504/collect_template_1_update_schema_summary_2021-03-17T09_22_21.xlsx)
