### ISSUE TITLE
Dropdown list extends past bottom of the page

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1248]
When a dropdown list is at the very end of the page, it will go through the bottom of the page, see this example
![image](https://user-images.githubusercontent.com/45661798/98961043-6a18b380-2505-11eb-98b5-1d14565cc33e.png)

![image](https://user-images.githubusercontent.com/45661798/98961130-8288ce00-2505-11eb-9a34-dc27c348c88c.png)

**Comment by minotogna** [comment]
Show dropdown on top if there's no enough space below
