### ISSUE TITLE
Relevant if field: automatic conversion of some XPath expressions into JS

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1249]
In survey import, fill in Relevant If field of entity / attribute with coded transformations in the following cases: 
1) there is no text: 'parent()' nor slash ('/') in XPath expression
2) apply_if is BLANK  (maybe this required?),
3) there are no functions in the expressions

TO DO THESE CONVERSIONS:
1)  = ->  ==
2) or -> ||
3) and -> &&
4) false(), FALSE, false -> 'false' (or whatever this is in JS)

Benefit is huge: for example survey 'collect_template_1' had 68 reported import issues, or which 26 could be automatically  
filled in with these rules & conversions.

**Comment by minotogna** [comment]
thus will be handled in https://app.clickup.com/t/ff5w5g
