### ISSUE TITLE
See Issue #702: Relevancy rule does not work in data entry

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1256]
The RELEVANCY rule is not working: I can still add data to "Non-forest" sites.

I imported a survey "1- BIOPHYSICAL SURVEY - CIRCULAR PLOT WITH MULTIPLE ENTITIES"
and in Collect Import Report there is line as follows:
Path: Cluster > Plots > Canopy Closure
Applicable if: plot_land_use/land_use='1'

**Comment by minotogna** [comment]
Data can still be entered at the moment. we will add a grey background to non relevant entities
