### ISSUE TITLE
Explorer: Swap order of entities

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1269]
Two issues:
1) Explorer does not show all atributes

2) Order of entities 
In Explorer view the user typically wants to get table that shows first the attributes for higher level entities, and after these the lower levels, i.e.
Cluster ID
Plot ID 
Tree ID
Tree species, three DBH , etc.

Now the selection list is in opposite order!
![image](https://user-images.githubusercontent.com/45661798/99255284-ff70bc00-2813-11eb-8c11-220e674e41ae.png)

**Comment by minotogna** [comment]
They are not in reverse order, that is the intended order.
The user select the entity and then the application shows all attributes from that entity to the root entity.
