### ISSUE TITLE
Import/Export icons?

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1275]
Are these icons correct or should they be swapped?

![image](https://user-images.githubusercontent.com/45661798/99498210-5d69e480-2977-11eb-81f4-94ba924ee33d.png)

**Comment by minotogna** [comment]
They are correct.

See [icon download](https://www.google.com/search?q=icon+download&client=safari&sxsrf=ALeKk01j9EZO4D1cXhf5Yk16V_GCVbCi9w:1605685521234&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjQrvTYzIvtAhVBCuwKHTyYAJUQ_AUoAXoECBIQAw&biw=2226&bih=1177)

and [icon upload](https://www.google.com/search?q=icon+upload&tbm=isch&ved=2ahUKEwjm5uPZzIvtAhUE_RoKHfe7DI8Q2-cCegQIABAA&oq=icon+upload&gs_lcp=CgNpbWcQAzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAA6BAgAEENQqdMDWKjgA2Cx4QNoAXAAeACAAUmIAbkDkgEBN5gBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=E9G0X6aRA4T6a_f3svgI&bih=1177&biw=2226&client=safari)
