### ISSUE TITLE
Import fails with survey containing no SRS

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1281]
Arena requires at least one SRS in survey properties.
In Collect, user can have a survey without SRSs. If this type of survey is imported, there is ERROR.

Here is a survey without SRS:
https://drive.google.com/file/d/1rinOWRytyIfVZGfedgIXN53km4ksgi-h/view?usp=sharing

Solution: EPSG 4326 can be default if no SRSs exists in the survey to be imported.

**Comment by SteRiccio** [comment]
the problem is more on the Collect side: in the survey mentioned there are some sampling points and they are associated to a srs that has been deleted in Collect; Collect should prevent the deletion of a srs, if it's the only one specified (default one).
