### ISSUE TITLE
Importing audio & video attributes: Max size and file type

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1307]
When survey contains FILE type attribute, with max. size, max size is not yet read, nor audio or video attribute specifications.
![image](https://user-images.githubusercontent.com/45661798/100728858-5e176780-33c8-11eb-8447-45b46b8b18a9.png)

Please check how IMAGE and DOCUMENT work as well.

**Comment by minotogna** [comment]
https://app.clickup.com/t/fx2q8k
