### ISSUE TITLE
Code attribute: "Show code" property

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1322]
For CODE attribute, we need an option (=property) that beside the label we also can see the code. This should be TRUE by default.

This should be also taken into account in Collect Import, because there is a similar property already in Collect schema.

An alternative solution is that the code is always shown in brackets before the label!

This is important to implement because some data entry persons do not know about the labels: they might enter data from field forms which contain only coded data.

**Comment by minotogna** [comment]
Always show code in () before label

**Comment by laurivesa** [comment]
Hi Mino. We should be able to see categorical variables without code too.
Especially in tables codes can harm.
Lauri

la 13. helmik. 2021 klo 13.41 Mino Togna <notifications@github.com>
kirjoitti:
