### ISSUE TITLE
Invite: User profile list is incomplete

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1324]
Advised by Ramiro, I tried to create a new invitation for myself with a different user profile, as "user". 
I am currently a System Administrator.
I cannot see more than these 2 groups in the list:   

![image](https://user-images.githubusercontent.com/45661798/101618010-af9ba400-3a11-11eb-812f-d70c2a1f447e.png)

**Comment by minotogna** [comment]
In order to invite users with different roles, survey must be published
