### ISSUE TITLE
Validation rule and list of attributes: show current attribute first (by its name or as $this in Xpath)

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1325]
Expression Editor in Validation works fine, and grouping too works fine. The issue is that the current (default) variable should be on the top of the dropdown list, even as single varaiable name even though it belongs to a group that is shown somewhere at the end of the list.
In the following picture the attribute name is "plot_slope" but it cannot be easily selected. 

![image](https://user-images.githubusercontent.com/45661798/101634791-7707c480-3a29-11eb-97eb-4dbea229acdd.png)

**Comment by SteRiccio** [comment]
solved with previous pull requests
