### ISSUE TITLE
Distance between two points

### ISSUE THREAD

**Issue by minotogna** [openforis/arena#1371]
add function distance() to calculate distance between two points.
use posting (GISRepository)
https://postgis.net/docs/ST_Distance.html

To calculate the distance:
https://stackoverflow.com/questions/18883601/function-to-calculate-distance-between-two-coordinates/18883819#18883819

**Comment by minotogna** [comment]
this will be handled in https://app.clickup.com/t/fv4n9e

**Comment by SteRiccio** [comment]
distance function added to custom functions.
E.g. distance(coordinate_attribute_1, coordinate_attribute_2)
