### ISSUE TITLE
Invite a user already invited with invited status triggers an error

### ISSUE THREAD

**Issue by minotogna** [openforis/arena#1382]
Ui should show a message "User already invited"

**Comment by ramirobg94** [comment]
As we have a System Error in the local environment the system crash,

on test environment the error is:

![Captura de pantalla 2021-02-16 a las 19 28 32](https://user-images.githubusercontent.com/11272068/108105794-5a24e880-708d-11eb-8fb7-f28437da57d1.png)

should we change the error code from 500 to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409
or leave as it is

**Comment by minotogna** [comment]
yes, change it to 409!
