### ISSUE TITLE
Schema Summary: add a column for 'Cycle'

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1677]
A schema can contain an attribute, that is valid for all cycles, or only for selected cycles. 
In Schema Summary (CSV) table there should be a new column showing the cycle(s) as a list, as follows: "1,2" or "1", or "2"

**Comment by ramirobg94** [comment]
The cycle 1 is 0 in database, 
what do you prefer to have into the CSV the value that we store into the database 
or the value that the user see on the screen


"0" -> Cycle 1
"1" -> Cycle 2
------
Cycles
"0,1" vs "1,2"

**Comment by laurivesa** [comment]
the value that the user sees, that is better.
