### ISSUE TITLE
See #1328: if Min or Max Count is blank, show DELETE button.

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1678]
Probably the reason is that 
MIN=MAX
This does not happen in every table. This works in another survey.
See survey: template_community_a
and table "product_unit"

**Comment by ramirobg94** [comment]
when min and max are not defined the delete button into the rows of the table is disabled.
this button shouldn't be disabled

![Captura de pantalla 2021-09-01 a las 9 45 18](https://user-images.githubusercontent.com/11272068/131632658-85a61f2e-27f6-4ccf-92f6-91d4412c3a96.png)

**Comment by SteRiccio** [comment]
The delete button is disabled when the min count of items is reached and they cannot be deleted in that case.
