### ISSUE TITLE
RStudio -Remote and clicking CANCEL: Do not start server

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1742]
When clicking RStudio Remote, and then CANCEL, this now starts RSTUDIO Server.  This should not happen! 
However, instance should not be terminated if it has been earlier started normally.

**Comment by ramirobg94** [comment]
I am not sure about what is the process to reproduce that, 
Here a video
- Cretate a remote instance
- Open the listed
- reopen this instance
- terminate this instance
- try to enter but the instances is stuck ( terminated)

https://user-images.githubusercontent.com/11272068/131539255-2ad5fc8f-b436-4838-8129-91364f5fbcc5.mov
