### ISSUE TITLE
003-read-data.R: Do not read result variables!

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#1745]
It is a mistake to read result variables in this script. Data should consists only of the original input data. Now there comes an error while running this script. 

these are all wrong command lines in my survey:
![image](https://user-images.githubusercontent.com/45661798/131507854-8f62e8c0-0f26-4289-8d62-0631a70f083c.png)

here is an error:
![image](https://user-images.githubusercontent.com/45661798/131507923-276ad356-bbde-44ee-b5fa-1bdbc7762804.png)

**Comment by ramirobg94** [comment]
could you share the survey?
