### ISSUE TITLE
Login as Survey EDITOR causes Error 500

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#2076]
update: Same error when login as Data Editor

![image](https://user-images.githubusercontent.com/45661798/152529917-98400efa-1a64-4484-8fd0-52dfcc374b9c.png)

![image](https://user-images.githubusercontent.com/45661798/152529959-df20a93f-6a41-4f3c-924f-f96be2aacf40.png)

**Comment by SteRiccio** [comment]
Error occurred when the user tried to access a forbidden module/url. Now those paths will show a "not found" page.
