### ISSUE TITLE
Data - Export (CSV): Categories labels with selected language

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#2097]
Currently, in case of multilingual language (EN-FR-ES), the exported CSV contains labels only in English, even if French or Spanish is selected. 

The exported zip file should contain language label in the file name, such as 
lauri_roska_export_2022-02-09_07-09-16.zip
--> lauri_roska_export_en_2022-02-09_07-09-16.zip
or 
lauri_roska_export_fr_2022-02-09_07-09-16.zip

**Comment by SteRiccio** [comment]
now in the CSV data export all category labels are exported in columns like label_en, label_es etc
