### ISSUE TITLE
CSV import: adding new entities. Do not stop importing process to invalid code

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#2681]
A tree data from CSV were tried to import. After 40 minutes run, there was an error about invalid code. 

  
![image](https://user-images.githubusercontent.com/45661798/213695475-6b7a0dd6-be53-49c0-ad93-5173d423a440.png)

**Comment by SteRiccio** [comment]
data import file validation has been added to check the validity of the file (faster) before performing the import (slower)
