### ISSUE TITLE
Categories, importing extra properties (01 -> 1)

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#2848]
Importing extra property as a text converts value 01 to 1, and this is wrong.
In "png_nfi_test" in Production, when importing sampling pint data and field "llg" was text, Arena CCV import converts to integer. For example input data:
![image](https://github.com/openforis/arena/assets/45661798/0c072946-94ab-4117-a04f-de2ad0e7d60d)

And value in Arena UI:
![image](https://github.com/openforis/arena/assets/45661798/6aa4dd14-b42a-4c36-bddb-14e224907cf4)

**Comment by SteRiccio** [comment]
text values like 001 should be quoted in the CSV file
