### ISSUE TITLE
API: UTF-8 character encoding is read wrong into entity data frames

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#2853]
"httr" library function GET is not reading texts not as UTF-8.
Categories are read correctly!
see example here:
![image](https://github.com/openforis/arena/assets/45661798/7d6422d8-057d-4fff-bd11-82c093635d02)

Problem is not in Arena data, because when it is exported into CSV, characters are all ok.
This is survey "amazonas" in Production.

**Comment by SteRiccio** [comment]
not related to Arean, but to the wrong format of the imported CSV file
