### ISSUE TITLE
Difficulty in updating the labels in an additional language for a survey in Arena

### ISSUE THREAD

**Issue by Falgoonee** [openforis/arena#2949]
In Arena, we currently have the option to **add languages** (along with English) for survey design. But it is difficult or no official way to update the labels in other languages currently. We need a way to export/import survey form labels, similar options we use in Collect for updating labels in other languages will be easier and great.

**Comment by SteRiccio** [comment]
solved by adding the possibility to import/export labels from the survey form designer
