### ISSUE TITLE
Issue with specifying"Other" field in multiple selection attributes

### ISSUE THREAD

**Issue by Falgoonee** [openforis/arena#2978]
In multiple selection attributes, if we select the "Other" option, Arena is not showing the "specify" field to enter the value/text manually. 
For example- 
the expression used- land_use_type.includes("11"), here 11 is the code of "other" but the specify field is not coming up to enter data.
<img width="286" alt="Screenshot 2023-08-21 113009" src="https://github.com/openforis/arena/assets/102762201/ed001e01-f520-4f22-aad1-667a42ced199">

**Comment by SteRiccio** [comment]
please use an expression like this: 
includes(land_use_type, '11')
Thanks!
