### ISSUE TITLE
Data export - Files: all files are not exported

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#3420]
There is an issue with exporting data with files. All files are not exported. Below comparison with the backup file:
 
Backup:
![image](https://github.com/openforis/arena/assets/45661798/45f6956f-aabf-4a16-bcd2-69b57f075739)

Exported data:
![image](https://github.com/openforis/arena/assets/45661798/bf9b4101-ff26-43e6-8784-e7f83aa4bde2)

**Comment by SteRiccio** [comment]
the backup file includes even files "marked as deleted"; when a file is deleted from the UI, it's only marked as deleted (so in could be restored, in theory, using the activity log).
When the data is exported as backup, all files are included, even the "deleted" ones; instead, when data is exported as CSV, only files in current data is exported.
