### ISSUE TITLE
Allow longer names on node_defs

### ISSUE THREAD

**Issue by ramirobg94** [openforis/arena#3672]
Please could we allow longer names on the nodedefs
<img width="608" alt="Captura de pantalla 2024-11-27 a las 18 31 25" src="https://github.com/user-attachments/assets/a4b1d75f-e142-4552-b167-8bd3f19cb1ed">

**Comment by SteRiccio** [comment]
The limit follows the limit of column length in PostgreSQL, so the answer, at least in the short term, is no!
