### ISSUE TITLE
Export of taxonomy - file name

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#697]
The exported taxonomy CSV file should contain the survey name, taxonomy list name, and preferably the export date.
Example of problem: I exported two taxonomy lists: 'tree' and 'bamboo'. I cannot detect from CSV file name which is which..

**Comment by minotogna** [comment]
Taxonomy Export file name must be [survey_name]_taxonomy_[taxonomy_list_name]_[date].csv
