### ISSUE TITLE
Expression editor: Allow usage of single entities attributes children of nodeDef context hierarchy 

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#702]
I imported a survey "1- BIOPHYSICAL SURVEY - CIRCULAR PLOT WITH MULTIPLE ENTITIES"
and in Collect Import Report there is line as follows:
Path: Cluster > Plots > Canopy Closure
Applicable if: plot_land_use/land_use='1'

In Expression Editor, there is no Land Use shown.

**Comment by minotogna** [comment]
We need to allow the use of attributes children of single entities that are part of the nodeDef context hierarchy. (I rename the issue accordingly)
