### ISSUE TITLE
Expression editor: the default attribute ($this)

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#703]
When adding validation rule(s) after importing a survey from Collect file, it is difficult to remember that to which attribute I am currently adding the rules. In the dropdown list of attributes in the Expression Editor, the first item on the top of the list could be the current attribute, as follows:
<THIS>
..followed by the list of attributes as they are now.  

(or something similar)

**Comment by minotogna** [comment]
1. we will make always visible the nodeDef name and type (probably above tab basic/advanced/validation.  (see #712)

2. We will make first attribute in the variables dropdown the current attribute (see #713)

3. I cannot see anything after you say ```....attribute, as follows:```
