### ISSUE TITLE
DataVis: Exported data fields order

### ISSUE THREAD

**Issue by minotogna** [openforis/arena#724]
Columns in exported CSV from DataVis must have the same order as table displayed (see attachment)

- [ ] add default order by uuid

![Screen Shot 2020-04-19 at 11 25 02](https://user-images.githubusercontent.com/1138156/79684327-a6ff1f00-8230-11ea-89a8-635349d9e680.png)

**Comment by SteRiccio** [comment]
This issue cannot be reproduced now, the DataVis has been changed already and both visualization and CSV export use the same query (sorted by date_modified if order by is not specified).
