### ISSUE TITLE
Delete empty survey - Error 500

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#734]
When deleted a survey "testi2" which contained no entities (so not published), got this error message:
ERROR 500
Could not serve: QueryResultError { code: queryResultErrorCode.noData message: "No data returned from the query." received: 0 query: "SELECT id, uuid, published, draft, props, props_draft, owner_uuid, to_char(date_created,'YYYY-MM-DD"T"HH24:MI:ssZ') as date_created, to_char(date_modified,'YYYY-MM-DD"T"HH24:MI:ssZ') as date_modified FROM survey WHERE id = '15'" }

Survey was deleted from this list.

**Comment by SteRiccio** [comment]
I cannot reproduce the error, maybe it occurred with an old version of the application and this error doesn't occur anymore in the latest version of Arena.
