### ISSUE TITLE
Collect Import: Error at stage 8 (Records Import)

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#735]
I tried to reimport on already existing survey in Arena from collect-backup file. There was no warnings, but import error with msg: 
"ReferenceError: Cannot access 'recordValidation' before initialization"

**Comment by minotogna** [comment]
Can you share with us the survey you tried to import? thanks!

**Comment by minotogna** [comment]
The collect backup file is available in our google drive folder and named as collect_template_1-2019-10-08T16_27_06.collect-backup

**Comment by SteRiccio** [comment]
it happened with an old version of the application
