### ISSUE TITLE
Collect Import: Checkbox / Dropdown from imported survey

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#736]
Request: In Arena there are two "Display as" options: Checkbox and Dropbown. 
In Collect there are three options:  1) Text, 2) Dropdown, 3) Radiobox / Checkbox.

For CODE type attribute, when imported, can we get Display As automatically into "Checkbox" if imported item is already Checkbox ?

**Comment by minotogna** [comment]
I close this since I added this to be fixed in issue #710
