### ISSUE TITLE
Expressions: Date / Time attribute: automatically default value or easy entry

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#751]
There should be an easy way to give to give the default value formula to date and time attributes. Now this in Xpath:
DATE idm:currentDate()
TIME: dm:currentTime()

Can the formula emerge automatically to the expression box, or can there be a hint?
Justification: these are VERY common default values in the data collection!

**Comment by minotogna** [comment]
Of course this as VERY common default values. We just haven't had the time yet to implement this!

**Comment by minotogna** [comment]
For date and time add ```now()``` function
