### ISSUE TITLE
Code - qualifier field missing?

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#772]
In Collect we had "Specify" option for code list items. How do we handle this in Arena? How do we get these fields imported into Arena database?
This has worked very well in Collect.
see e.g.
http://www.openforis.org/support/questions/2210/field-to-specify-mandatory

**Comment by minotogna** [comment]
You can add another attribute and set the Relevant if ```codeAttribute = codeOhter```.
This is automatically generated when you import the survey from collect.

The advantage of this approach is that the attribute used to enter the text 'other' can be used as a normal attribute. e.g. you can validate it, use a specific data type, etc...

**Comment by SteRiccio** [comment]
also the approach of Arena simplify the access to the `qualifier` field; for example in Collect you had to write something like `code_attribute_name@qualifier` to access that value, instead in Arena you will access it as a regular text attribute and you can use it easily in other expressions.
