### ISSUE TITLE
Form Designer - code attribute - ADD button behavior

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#827]
In Form Designer in case of code variable, I have already category selected. I just happen to click ADD button, and want to cancel (either by clicking return in browser, or DONE in UI), then the "category" disappears. 
It should remain as set earlier. 

2) If I click DONE (without filling in nothing) and look at MANAGE, I see a new INVALID-UNUSED code list.

**Comment by SteRiccio** [comment]
fixed by #1711
