### ISSUE TITLE
Boolean attribute: YES/NO

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#839]
Boolean attribute is now shown as TRUE-FALSE
However, sometimes the answer should be YES-NO.
can this be implemented?

**Comment by minotogna** [comment]
- [ ] In NodeDefEdit under Description fields add field Button Labels with two buttons: True/False and Yes/No (Default selection is True/False)
- [ ] In NodeDefEdit->Advanced->Default values: when const is selected show buttons with selected Button labels
- [ ] In SurveyForm show checkbox with selected Button labels
- [ ] In DataVisualization (view and export) show value with selected Button labels
