### ISSUE TITLE
File attribute: Download button

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#942]
This maybe only happening in PREVIEW mode, but I do not see DOWNLOAD (=export) button. There is only UPLOAD button. We should be able to download a file, for example a Word report out from the database.

**Comment by minotogna** [comment]
If you click on the file name, you download the file (see screenshot)

<img width="1440" alt="Screen Shot 2020-07-31 at 09 16 03" src="https://user-images.githubusercontent.com/1138156/89010274-89048880-d30e-11ea-85fb-3c66909747d8.png">
