### ISSUE TITLE
Form designer-Default value-Advanced (JavaScript)

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#943]
would it be possible to validate the JavaScript?

**Comment by minotogna** [comment]
It is already validating in real time (see screenshot), or am I misunderstanding the question?

<img width="1018" alt="Screen Shot 2020-07-31 at 09 13 40" src="https://user-images.githubusercontent.com/1138156/89010066-31feb380-d30e-11ea-8c30-65e92f21a2f0.png">
