### ISSUE TITLE
Opening page after login to Arena

### ISSUE THREAD

**Issue by laurivesa** [openforis/arena#948]
There should be an "opening/welcome page" after login. Now when I have exited last time in Form Designer, Arena opens next time the same survey editor. I want to select my survey and operation what I want to do.

**Comment by minotogna** [comment]
The default behavior is: after login user open current page.
This is very useful when user add a bookmark of a specific page; after long inactive period user is not logged in anymore and clicking that bookmark renders login and after login user will see the bookmarked page.
With a welcome page this behavior will broke.

Also, many users will have access to only one survey and redirecting them in the survey selection page would not make sense to me.
